var searchData=
[
  ['hala',['hala',['../namespacehala.html',1,'hala'],['../group__HALA.html',1,'(Global Namespace)']]],
  ['hala_2eh',['hala.h',['../hala_8h.html',1,'']]],
  ['hala_2ehpp',['hala.hpp',['../hala_8hpp.html',1,'']]],
  ['hala_5fabs',['hala_abs',['../group__HALACTYPES.html#gaeee99633ebb74762ab996c1672f2c805',1,'hala']]],
  ['hala_5fblas_2ehpp',['hala_blas.hpp',['../hala__blas_8hpp.html',1,'']]],
  ['hala_5fcholmod_2ehpp',['hala_cholmod.hpp',['../hala__cholmod_8hpp.html',1,'']]],
  ['hala_5fcuda_2ehpp',['hala_cuda.hpp',['../hala__cuda_8hpp.html',1,'']]],
  ['hala_5fenable_5fblas',['HALA_ENABLE_BLAS',['../hala__blas_8hpp.html#a5263bf25ea0a23df6d07693023e3a1e8',1,'hala_blas.hpp']]],
  ['hala_5fgpu_2ehpp',['hala_gpu.hpp',['../hala__gpu_8hpp.html',1,'']]],
  ['hala_5fgpu_5fvector_2ehpp',['hala_gpu_vector.hpp',['../hala__gpu__vector_8hpp.html',1,'']]],
  ['hala_5fgpu_5fwrap_5farray_2ehpp',['hala_gpu_wrap_array.hpp',['../hala__gpu__wrap__array_8hpp.html',1,'']]],
  ['hala_5fint',['hala_int',['../namespacehala.html#acb09081de2bccbc9add2b253d4793368',1,'hala']]],
  ['hala_5flapack_2ehpp',['hala_lapack.hpp',['../hala__lapack_8hpp.html',1,'']]],
  ['hala_5frocm_2ehpp',['hala_rocm.hpp',['../hala__rocm_8hpp.html',1,'']]],
  ['hala_5fsize',['hala_size',['../namespacehala.html#a98850706b7be2eb74266c994d1030a37',1,'hala']]],
  ['hala_5fsolvers_2ehpp',['hala_solvers.hpp',['../hala__solvers_8hpp.html',1,'']]],
  ['hala_5fversion_5fmajor',['HALA_VERSION_MAJOR',['../group__HALACORE.html#ga5362fb3880c02e876fae6398dbeadb26',1,'hala_core.hpp']]],
  ['hala_5fversion_5fminor',['HALA_VERSION_MINOR',['../group__HALACORE.html#gafd00610a020abdab868a305cef4a0646',1,'hala_core.hpp']]],
  ['hala_5fversion_5fpatch',['HALA_VERSION_PATCH',['../group__HALACORE.html#ga8b0c932cdaf83f45d2aa1549f991a0c2',1,'hala_core.hpp']]],
  ['hala_5fwrap_5farray_2ehpp',['hala_wrap_array.hpp',['../hala__wrap__array_8hpp.html',1,'']]],
  ['hala_20blas_20wrapper_20templates',['HALA BLAS Wrapper Templates',['../group__HALABLAS.html',1,'']]],
  ['hala_20cholmod_20wrapper_20templates',['HALA Cholmod Wrapper Templates',['../group__HALACHOLMOD.html',1,'']]],
  ['hala_20helper_20templates',['HALA Helper Templates',['../group__HALACORE.html',1,'']]],
  ['hala_20cuda_20wrapper_20templates',['HALA CUDA Wrapper Templates',['../group__HALACUDA.html',1,'']]],
  ['hala_20support_20for_20custom_20vector_20class',['HALA Support for Custom Vector Class',['../group__HALACUSTOM.html',1,'']]],
  ['hala_20examples',['HALA Examples',['../group__HALAEXAMPLE.html',1,'']]],
  ['hala_20cuda_20and_20rocm_20wrapper_20templates',['HALA CUDA and ROCM Wrapper Templates',['../group__HALAGPU.html',1,'']]],
  ['hala_20lapack_20wrapper_20templates',['HALA LAPACK Wrapper Templates',['../group__HALALAPACK.html',1,'']]],
  ['hala_20miscellaneous_20methods',['HALA Miscellaneous Methods',['../group__HALAMISC.html',1,'']]],
  ['hala_20rocm_20wrapper_20templates',['HALA ROCM Wrapper Templates',['../group__HALAROCM.html',1,'']]],
  ['hala_20solver_20algorithms',['HALA Solver Algorithms',['../group__HALASOLVERS.html',1,'']]],
  ['hala_20sparse_20matrix_20templates',['HALA Sparse Matrix Templates',['../group__HALASPARSE.html',1,'']]],
  ['hala_20advanced_20vector_20extensions',['HALA Advanced Vector Extensions',['../group__HALAVEX.html',1,'']]],
  ['hala_20wrapped_20accelerated_20extensions',['HALA Wrapped Accelerated Extensions',['../group__HALAWAXEXT.html',1,'']]],
  ['has_5fresize',['has_resize',['../structhala_1_1has__resize.html',1,'hala']]],
  ['hermitian_5ftrans',['hermitian_trans',['../namespacehala.html#a1a80b31f00e6b57b9fdcfee9e2db0014',1,'hala']]],
  ['host2device',['host2device',['../namespacehala.html#a37f4d8a83828612055f625f0523ad667a2b5f960e5534a6b7454f84eff0c00338',1,'hala']]],
  ['host_5fpntr',['host_pntr',['../structhala_1_1host__pntr.html',1,'hala']]],
  ['hala',['HALA',['../index.html',1,'']]],
  ['valid',['valid',['../namespacehala_1_1valid.html',1,'hala']]]
];
