#ifndef __HALA_CONFIG_HPP
#define __HALA_CONFIG_HPP
/*
 * Code Author: Miroslav Stoyanov
 *
 * Copyright (C) 2018  Miroslav Stoyanov
 *
 * This file is part of
 * Hardware Accelerated Linear Algebra (HALA)
 *
 */

/*!
 * \internal
 * \ingroup HALACMAKE
 * \file hala_config.hpp
 * \brief HALA configuration options, generated by CMake.
 * \author Miroslav Stoyanov
 * \copyright BSD-3-Clause
 *
 * \par Configuration Header
 * This files is configured with CMake configure_file() method
 * and contains all information about existing libraries, alignment, etc.
 * \endinternal
 */

/*!
 * \internal
 * \ingroup HALA
 * \addtogroup HALACMAKE Configuration options from CMake.
 *
 * The options passed to CMake will be written to hala_config.hpp
 * which will be included through the main header hala.hpp.
 *
 * The version and license are re-defined in hala_core.hpp in case the modules
 * are used separately and each of the module headers re-defined the corresponding
 * ENABLE variable. The alignment variables are not defined in other places.
 * \endinternal
 */

/*!
 * \ingroup HALACMAKE
 * \brief Defines whether CUDA is available.
 */
#cmakedefine HALA_ENABLE_CUDA
/*!
 * \ingroup HALACMAKE
 * \brief Defines whether ROCM is available.
 */
#cmakedefine HALA_ENABLE_ROCM
/*!
 * \ingroup HALACMAKE
 * \brief Defines if either CUDA or ROCM is enabled, which introduces gpu_engine, gpu_vector, and gpu methods.
 */
#cmakedefine HALA_ENABLE_GPU
/*!
 * \ingroup HALACMAKE
 * \brief Defines whether CHOLMOD is available.
 */
#cmakedefine HALA_ENABLE_CHOLMOD

/*!
 * \ingroup HALACMAKE
 * \brief Defines whether the compiler aligns to 128-bits by default.
 */
#cmakedefine HALA_ALIGN128
/*!
 * \ingroup HALACMAKE
 * \brief Defines whether the compiler aligns to 256-bits by default.
 */
#cmakedefine HALA_ALIGN256
/*!
 * \ingroup HALACMAKE
 * \brief Defines whether the compiler aligns to 512-bits by default.
 */
#cmakedefine HALA_ALIGN512

/*!
 * \ingroup HALACMAKE
 * \brief Defines whether the human readable license.
 */
#define HALA_LICENSE "@hala_license@"

/*!
 * \ingroup HALACMAKE
 * \brief The major component of the version.
 */
#define HALA_VERSION_MAJOR @HALA_VERSION_MAJOR@

/*!
 * \ingroup HALACMAKE
 * \brief The major component of the version.
 */
#define HALA_VERSION_MINOR @HALA_VERSION_MINOR@

/*!
 * \ingroup HALACMAKE
 * \brief The major component of the version.
 */
#define HALA_VERSION_PATCH @HALA_VERSION_PATCH@

/*!
 * \ingroup HALACMAKE
 * \brief Check if BLAS supports the csyr2/zsyr2 extensions.
 */
#cmakedefine HALA_HAS_ZSYR2

/*!
 * \ingroup HALACMAKE
 * \brief Check if BLAS supports the cspr2/zspr2 extensions.
 */
#cmakedefine HALA_HAS_ZSPR2

/*!
 * \ingroup HALACMAKE
 * \brief Check if BLAS supports the csbmv/csbmv extensions.
 */
#cmakedefine HALA_HAS_ZSBMV

#endif
